### ISSUE TITLE
camera_paths/your_trajectory.json

### ISSUE THREAD

**Issue by lkk123841** [water-splatting/water-splatting#2]
Hello author, when I was trying to render a video using your data, I did not find the “IUI3-RedSea/camera_paths/your_trajectory.json” as instructed in the command. Do I need to generate it myself, or do you have a specific method for this, as I was unable to run it successfully with a json file I generated myself.

**Comment by IronLu11** [comment]
Hi. You could use ns-viewer to generate a json file.

**Comment by lkk123841** [comment]
Thank you for your reply. I will try it out.



---- Replied Message ----
| From | Li ***@***.***> |
| Date | 09/27/2024 21:37 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [water-splatting/water-splatting] camera_paths/your_trajectory.json (Issue #2) |

Hi. You can use ns-viewer to generate a json file.
