### ISSUE TITLE
no water-splatting in ns-train

### ISSUE THREAD

**Issue by Zhangxr02** [water-splatting/water-splatting#4]
Hello,

I encountered a problem while replicating your method. Everything was normal during the previous installation. But when I executed the step of "**ns-train water plating - vis viewer+wandb colmap - downscale factor 1- colmap path sparse/0- data/your_path_to-udataset/SathruNeRF_dataset/UI3 RedSea - images-path Images_wb**", it showed that there was no water-splatting in ns-train. Could you help me?

Thanks!
![图片1](https://github.com/user-attachments/assets/bb50d299-97e7-4623-a9a7-7ccf355efb14)

**Comment by BoZhiStudying233** [comment]
I meet the same problem, did you solve it?

**Comment by BoZhiStudying233** [comment]
I re-ran `pip install --no-use-pep517 -e `in the repository folder.
Then I can use this` ns-train water-splatting`
